/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ERP System API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary Login with email and password
 */
export const LoginBody = zod.object({
  email: zod.string(),
  password: zod.string(),
});

export const LoginResponse = zod.object({
  user: zod.object({
    id: zod.number(),
    email: zod.string(),
    fullName: zod.string(),
    role: zod.string(),
    departmentId: zod.number().nullish(),
    departmentName: zod.string().nullish(),
    position: zod.string().nullish(),
    phone: zod.string().nullish(),
    emergencyContact: zod.string().nullish(),
    avatarUrl: zod.string().nullish(),
    employmentStatus: zod.string(),
    joinDate: zod.string().nullish(),
    createdAt: zod.string(),
  }),
  token: zod.string(),
});

/**
 * @summary Logout current session
 */
export const LogoutResponse = zod.object({
  message: zod.string(),
});

/**
 * @summary Get current authenticated user
 */
export const GetMeResponse = zod.object({
  id: zod.number(),
  email: zod.string(),
  fullName: zod.string(),
  role: zod.string(),
  departmentId: zod.number().nullish(),
  departmentName: zod.string().nullish(),
  position: zod.string().nullish(),
  phone: zod.string().nullish(),
  emergencyContact: zod.string().nullish(),
  avatarUrl: zod.string().nullish(),
  employmentStatus: zod.string(),
  joinDate: zod.string().nullish(),
  createdAt: zod.string(),
});

/**
 * @summary Change password
 */
export const ChangePasswordBody = zod.object({
  currentPassword: zod.string(),
  newPassword: zod.string(),
});

export const ChangePasswordResponse = zod.object({
  message: zod.string(),
});

/**
 * @summary List all users/employees
 */
export const ListUsersQueryParams = zod.object({
  departmentId: zod.coerce.number().nullish(),
  role: zod.coerce.string().nullish(),
  status: zod.coerce.string().nullish(),
  search: zod.coerce.string().nullish(),
});

export const ListUsersResponseItem = zod.object({
  id: zod.number(),
  email: zod.string(),
  fullName: zod.string(),
  role: zod.string(),
  departmentId: zod.number().nullish(),
  departmentName: zod.string().nullish(),
  position: zod.string().nullish(),
  phone: zod.string().nullish(),
  avatarUrl: zod.string().nullish(),
  employmentStatus: zod.string(),
  joinDate: zod.string().nullish(),
  createdAt: zod.string(),
});
export const ListUsersResponse = zod.array(ListUsersResponseItem);

/**
 * @summary Create / invite a new employee or admin
 */
export const CreateUserBody = zod.object({
  email: zod.string(),
  fullName: zod.string(),
  role: zod.string(),
  departmentId: zod.number().nullish(),
  position: zod.string().nullish(),
  phone: zod.string().nullish(),
  joinDate: zod.string().nullish(),
  password: zod.string(),
});

/**
 * @summary Get user by ID
 */
export const GetUserParams = zod.object({
  id: zod.coerce.number(),
});

export const GetUserResponse = zod.object({
  id: zod.number(),
  email: zod.string(),
  fullName: zod.string(),
  role: zod.string(),
  departmentId: zod.number().nullish(),
  departmentName: zod.string().nullish(),
  position: zod.string().nullish(),
  phone: zod.string().nullish(),
  emergencyContact: zod.string().nullish(),
  avatarUrl: zod.string().nullish(),
  employmentStatus: zod.string(),
  joinDate: zod.string().nullish(),
  createdAt: zod.string(),
});

/**
 * @summary Update user profile
 */
export const UpdateUserParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateUserBody = zod.object({
  fullName: zod.string().nullish(),
  departmentId: zod.number().nullish(),
  position: zod.string().nullish(),
  phone: zod.string().nullish(),
  emergencyContact: zod.string().nullish(),
  avatarUrl: zod.string().nullish(),
  joinDate: zod.string().nullish(),
  employmentStatus: zod.string().nullish(),
});

export const UpdateUserResponse = zod.object({
  id: zod.number(),
  email: zod.string(),
  fullName: zod.string(),
  role: zod.string(),
  departmentId: zod.number().nullish(),
  departmentName: zod.string().nullish(),
  position: zod.string().nullish(),
  phone: zod.string().nullish(),
  avatarUrl: zod.string().nullish(),
  employmentStatus: zod.string(),
  joinDate: zod.string().nullish(),
  createdAt: zod.string(),
});

/**
 * @summary Deactivate a user
 */
export const DeactivateUserParams = zod.object({
  id: zod.coerce.number(),
});

export const DeactivateUserResponse = zod.object({
  message: zod.string(),
});

/**
 * @summary Employee headcount stats per department and role
 */
export const GetUserStatsResponse = zod.object({
  total: zod.number(),
  byDepartment: zod.array(
    zod.object({
      departmentId: zod.number(),
      departmentName: zod.string(),
      count: zod.number(),
    }),
  ),
  byRole: zod.array(
    zod.object({
      role: zod.string(),
      count: zod.number(),
    }),
  ),
  activeCount: zod.number(),
  newThisMonth: zod.number(),
});

/**
 * @summary List all departments
 */
export const ListDepartmentsResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  slug: zod.string(),
  headUserId: zod.number().nullish(),
  headUserName: zod.string().nullish(),
  employeeCount: zod.number(),
  createdAt: zod.string(),
});
export const ListDepartmentsResponse = zod.array(ListDepartmentsResponseItem);

/**
 * @summary Create a department
 */
export const CreateDepartmentBody = zod.object({
  name: zod.string(),
  slug: zod.string(),
  headUserId: zod.number().nullish(),
});

/**
 * @summary Get department by ID
 */
export const GetDepartmentParams = zod.object({
  id: zod.coerce.number(),
});

export const GetDepartmentResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  slug: zod.string(),
  headUserId: zod.number().nullish(),
  headUserName: zod.string().nullish(),
  employeeCount: zod.number(),
  createdAt: zod.string(),
});

/**
 * @summary Update department
 */
export const UpdateDepartmentParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateDepartmentBody = zod.object({
  name: zod.string().nullish(),
  headUserId: zod.number().nullish(),
});

export const UpdateDepartmentResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  slug: zod.string(),
  headUserId: zod.number().nullish(),
  headUserName: zod.string().nullish(),
  employeeCount: zod.number(),
  createdAt: zod.string(),
});

/**
 * @summary List attendance records
 */
export const ListAttendanceQueryParams = zod.object({
  userId: zod.coerce.number().nullish(),
  departmentId: zod.coerce.number().nullish(),
  startDate: zod.coerce.string().nullish(),
  endDate: zod.coerce.string().nullish(),
});

export const ListAttendanceResponseItem = zod.object({
  id: zod.number(),
  userId: zod.number(),
  userFullName: zod.string().nullish(),
  date: zod.string(),
  clockInAt: zod.string().nullish(),
  clockOutAt: zod.string().nullish(),
  isLate: zod.boolean(),
  notes: zod.string().nullish(),
  createdAt: zod.string(),
});
export const ListAttendanceResponse = zod.array(ListAttendanceResponseItem);

/**
 * @summary Clock out for today
 */
export const ClockOutResponse = zod.object({
  id: zod.number(),
  userId: zod.number(),
  userFullName: zod.string().nullish(),
  date: zod.string(),
  clockInAt: zod.string().nullish(),
  clockOutAt: zod.string().nullish(),
  isLate: zod.boolean(),
  notes: zod.string().nullish(),
  createdAt: zod.string(),
});

/**
 * @summary Get today's attendance for current user
 */
export const GetTodayAttendanceResponse = zod.object({
  id: zod.number(),
  userId: zod.number(),
  userFullName: zod.string().nullish(),
  date: zod.string(),
  clockInAt: zod.string().nullish(),
  clockOutAt: zod.string().nullish(),
  isLate: zod.boolean(),
  notes: zod.string().nullish(),
  createdAt: zod.string(),
});

/**
 * @summary Monthly attendance summary per employee
 */
export const GetAttendanceSummaryQueryParams = zod.object({
  month: zod.coerce.number(),
  year: zod.coerce.number(),
  departmentId: zod.coerce.number().nullish(),
});

export const GetAttendanceSummaryResponseItem = zod.object({
  userId: zod.number(),
  userFullName: zod.string(),
  departmentName: zod.string(),
  presentDays: zod.number(),
  absentDays: zod.number(),
  lateDays: zod.number(),
  workingDays: zod.number(),
});
export const GetAttendanceSummaryResponse = zod.array(
  GetAttendanceSummaryResponseItem,
);

/**
 * @summary List leave applications
 */
export const ListLeaveQueryParams = zod.object({
  userId: zod.coerce.number().nullish(),
  departmentId: zod.coerce.number().nullish(),
  status: zod.coerce.string().nullish(),
});

export const ListLeaveResponseItem = zod.object({
  id: zod.number(),
  userId: zod.number(),
  userFullName: zod.string().nullish(),
  departmentId: zod.number(),
  departmentName: zod.string().nullish(),
  leaveType: zod.string(),
  startDate: zod.string(),
  endDate: zod.string(),
  daysCount: zod.number(),
  reason: zod.string(),
  status: zod.string(),
  reviewedBy: zod.number().nullish(),
  reviewerName: zod.string().nullish(),
  reviewerRemarks: zod.string().nullish(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});
export const ListLeaveResponse = zod.array(ListLeaveResponseItem);

/**
 * @summary Submit a leave application
 */
export const CreateLeaveBody = zod.object({
  leaveType: zod.string(),
  startDate: zod.string(),
  endDate: zod.string(),
  reason: zod.string(),
});

/**
 * @summary Get leave application by ID
 */
export const GetLeaveParams = zod.object({
  id: zod.coerce.number(),
});

export const GetLeaveResponse = zod.object({
  id: zod.number(),
  userId: zod.number(),
  userFullName: zod.string().nullish(),
  departmentId: zod.number(),
  departmentName: zod.string().nullish(),
  leaveType: zod.string(),
  startDate: zod.string(),
  endDate: zod.string(),
  daysCount: zod.number(),
  reason: zod.string(),
  status: zod.string(),
  reviewedBy: zod.number().nullish(),
  reviewerName: zod.string().nullish(),
  reviewerRemarks: zod.string().nullish(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});

/**
 * @summary Approve or reject a leave application
 */
export const UpdateLeaveParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateLeaveBody = zod.object({
  status: zod.string(),
  reviewerRemarks: zod.string().nullish(),
});

export const UpdateLeaveResponse = zod.object({
  id: zod.number(),
  userId: zod.number(),
  userFullName: zod.string().nullish(),
  departmentId: zod.number(),
  departmentName: zod.string().nullish(),
  leaveType: zod.string(),
  startDate: zod.string(),
  endDate: zod.string(),
  daysCount: zod.number(),
  reason: zod.string(),
  status: zod.string(),
  reviewedBy: zod.number().nullish(),
  reviewerName: zod.string().nullish(),
  reviewerRemarks: zod.string().nullish(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});

/**
 * @summary Get leave balances for a user
 */
export const GetLeaveBalancesParams = zod.object({
  userId: zod.coerce.number(),
});

export const GetLeaveBalancesResponseItem = zod.object({
  id: zod.number(),
  userId: zod.number(),
  leaveType: zod.string(),
  allocated: zod.number(),
  used: zod.number(),
  remaining: zod.number(),
  year: zod.number(),
});
export const GetLeaveBalancesResponse = zod.array(GetLeaveBalancesResponseItem);

/**
 * @summary List complaints
 */
export const ListComplaintsQueryParams = zod.object({
  departmentId: zod.coerce.number().nullish(),
  status: zod.coerce.string().nullish(),
});

export const ListComplaintsResponseItem = zod.object({
  id: zod.number(),
  userId: zod.number(),
  userFullName: zod.string().nullish(),
  departmentId: zod.number(),
  departmentName: zod.string().nullish(),
  category: zod.string(),
  title: zod.string(),
  description: zod.string(),
  isAnonymous: zod.boolean(),
  status: zod.string(),
  assignedTo: zod.number().nullish(),
  assignedToName: zod.string().nullish(),
  response: zod.string().nullish(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});
export const ListComplaintsResponse = zod.array(ListComplaintsResponseItem);

/**
 * @summary Submit a complaint
 */
export const CreateComplaintBody = zod.object({
  category: zod.string(),
  title: zod.string(),
  description: zod.string(),
  isAnonymous: zod.boolean(),
});

/**
 * @summary Get complaint by ID
 */
export const GetComplaintParams = zod.object({
  id: zod.coerce.number(),
});

export const GetComplaintResponse = zod.object({
  id: zod.number(),
  userId: zod.number(),
  userFullName: zod.string().nullish(),
  departmentId: zod.number(),
  departmentName: zod.string().nullish(),
  category: zod.string(),
  title: zod.string(),
  description: zod.string(),
  isAnonymous: zod.boolean(),
  status: zod.string(),
  assignedTo: zod.number().nullish(),
  assignedToName: zod.string().nullish(),
  response: zod.string().nullish(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});

/**
 * @summary Update complaint status or response
 */
export const UpdateComplaintParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateComplaintBody = zod.object({
  status: zod.string().nullish(),
  response: zod.string().nullish(),
  assignedTo: zod.number().nullish(),
});

export const UpdateComplaintResponse = zod.object({
  id: zod.number(),
  userId: zod.number(),
  userFullName: zod.string().nullish(),
  departmentId: zod.number(),
  departmentName: zod.string().nullish(),
  category: zod.string(),
  title: zod.string(),
  description: zod.string(),
  isAnonymous: zod.boolean(),
  status: zod.string(),
  assignedTo: zod.number().nullish(),
  assignedToName: zod.string().nullish(),
  response: zod.string().nullish(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});

/**
 * @summary List requests
 */
export const ListRequestsQueryParams = zod.object({
  departmentId: zod.coerce.number().nullish(),
  status: zod.coerce.string().nullish(),
  userId: zod.coerce.number().nullish(),
});

export const ListRequestsResponseItem = zod.object({
  id: zod.number(),
  userId: zod.number(),
  userFullName: zod.string().nullish(),
  departmentId: zod.number(),
  departmentName: zod.string().nullish(),
  requestType: zod.string(),
  title: zod.string(),
  description: zod.string(),
  status: zod.string(),
  reviewedBy: zod.number().nullish(),
  reviewerName: zod.string().nullish(),
  reviewerRemarks: zod.string().nullish(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});
export const ListRequestsResponse = zod.array(ListRequestsResponseItem);

/**
 * @summary Submit a request
 */
export const CreateRequestBody = zod.object({
  requestType: zod.string(),
  title: zod.string(),
  description: zod.string(),
});

/**
 * @summary Get request by ID
 */
export const GetRequestParams = zod.object({
  id: zod.coerce.number(),
});

export const GetRequestResponse = zod.object({
  id: zod.number(),
  userId: zod.number(),
  userFullName: zod.string().nullish(),
  departmentId: zod.number(),
  departmentName: zod.string().nullish(),
  requestType: zod.string(),
  title: zod.string(),
  description: zod.string(),
  status: zod.string(),
  reviewedBy: zod.number().nullish(),
  reviewerName: zod.string().nullish(),
  reviewerRemarks: zod.string().nullish(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});

/**
 * @summary Approve or reject a request
 */
export const UpdateRequestParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateRequestBody = zod.object({
  status: zod.string(),
  reviewerRemarks: zod.string().nullish(),
});

export const UpdateRequestResponse = zod.object({
  id: zod.number(),
  userId: zod.number(),
  userFullName: zod.string().nullish(),
  departmentId: zod.number(),
  departmentName: zod.string().nullish(),
  requestType: zod.string(),
  title: zod.string(),
  description: zod.string(),
  status: zod.string(),
  reviewedBy: zod.number().nullish(),
  reviewerName: zod.string().nullish(),
  reviewerRemarks: zod.string().nullish(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});

/**
 * @summary List payroll records
 */
export const ListPayrollQueryParams = zod.object({
  userId: zod.coerce.number().nullish(),
  departmentId: zod.coerce.number().nullish(),
  month: zod.coerce.number().nullish(),
  year: zod.coerce.number().nullish(),
  status: zod.coerce.string().nullish(),
});

export const ListPayrollResponseItem = zod.object({
  id: zod.number(),
  userId: zod.number(),
  userFullName: zod.string().nullish(),
  departmentName: zod.string().nullish(),
  month: zod.number(),
  year: zod.number(),
  baseSalary: zod.number(),
  allowances: zod.number(),
  bonuses: zod.number(),
  deductions: zod.number(),
  netSalary: zod.number(),
  status: zod.string(),
  approvedBy: zod.number().nullish(),
  approvedByName: zod.string().nullish(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});
export const ListPayrollResponse = zod.array(ListPayrollResponseItem);

/**
 * @summary Create a payroll record
 */
export const CreatePayrollBody = zod.object({
  userId: zod.number(),
  month: zod.number(),
  year: zod.number(),
  baseSalary: zod.number(),
  allowances: zod.number(),
  bonuses: zod.number(),
  deductions: zod.number(),
});

/**
 * @summary Get payroll record by ID
 */
export const GetPayrollParams = zod.object({
  id: zod.coerce.number(),
});

export const GetPayrollResponse = zod.object({
  id: zod.number(),
  userId: zod.number(),
  userFullName: zod.string().nullish(),
  departmentName: zod.string().nullish(),
  month: zod.number(),
  year: zod.number(),
  baseSalary: zod.number(),
  allowances: zod.number(),
  bonuses: zod.number(),
  deductions: zod.number(),
  netSalary: zod.number(),
  status: zod.string(),
  approvedBy: zod.number().nullish(),
  approvedByName: zod.string().nullish(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});

/**
 * @summary Update a payroll record
 */
export const UpdatePayrollParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdatePayrollBody = zod.object({
  baseSalary: zod.number().nullish(),
  allowances: zod.number().nullish(),
  bonuses: zod.number().nullish(),
  deductions: zod.number().nullish(),
  status: zod.string().nullish(),
});

export const UpdatePayrollResponse = zod.object({
  id: zod.number(),
  userId: zod.number(),
  userFullName: zod.string().nullish(),
  departmentName: zod.string().nullish(),
  month: zod.number(),
  year: zod.number(),
  baseSalary: zod.number(),
  allowances: zod.number(),
  bonuses: zod.number(),
  deductions: zod.number(),
  netSalary: zod.number(),
  status: zod.string(),
  approvedBy: zod.number().nullish(),
  approvedByName: zod.string().nullish(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});

/**
 * @summary Approve a payroll record (Super Admin only)
 */
export const ApprovePayrollParams = zod.object({
  id: zod.coerce.number(),
});

export const ApprovePayrollResponse = zod.object({
  id: zod.number(),
  userId: zod.number(),
  userFullName: zod.string().nullish(),
  departmentName: zod.string().nullish(),
  month: zod.number(),
  year: zod.number(),
  baseSalary: zod.number(),
  allowances: zod.number(),
  bonuses: zod.number(),
  deductions: zod.number(),
  netSalary: zod.number(),
  status: zod.string(),
  approvedBy: zod.number().nullish(),
  approvedByName: zod.string().nullish(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});

/**
 * @summary Payroll summary by department for a given month/year
 */
export const GetPayrollSummaryQueryParams = zod.object({
  month: zod.coerce.number(),
  year: zod.coerce.number(),
});

export const GetPayrollSummaryResponseItem = zod.object({
  departmentId: zod.number(),
  departmentName: zod.string(),
  totalNetSalary: zod.number(),
  employeeCount: zod.number(),
  approvedCount: zod.number(),
  pendingCount: zod.number(),
});
export const GetPayrollSummaryResponse = zod.array(
  GetPayrollSummaryResponseItem,
);

/**
 * @summary List projects
 */
export const ListProjectsQueryParams = zod.object({
  departmentId: zod.coerce.number().nullish(),
  status: zod.coerce.string().nullish(),
});

export const ListProjectsResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  description: zod.string().nullish(),
  departmentId: zod.number().nullish(),
  departmentName: zod.string().nullish(),
  status: zod.string(),
  createdBy: zod.number(),
  startDate: zod.string().nullish(),
  endDate: zod.string().nullish(),
  taskCount: zod.number(),
  completedTaskCount: zod.number(),
  createdAt: zod.string(),
});
export const ListProjectsResponse = zod.array(ListProjectsResponseItem);

/**
 * @summary Create a project
 */
export const CreateProjectBody = zod.object({
  name: zod.string(),
  description: zod.string().nullish(),
  departmentId: zod.number().nullish(),
  startDate: zod.string().nullish(),
  endDate: zod.string().nullish(),
});

/**
 * @summary Get project by ID
 */
export const GetProjectParams = zod.object({
  id: zod.coerce.number(),
});

export const GetProjectResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  description: zod.string().nullish(),
  departmentId: zod.number().nullish(),
  departmentName: zod.string().nullish(),
  status: zod.string(),
  createdBy: zod.number(),
  startDate: zod.string().nullish(),
  endDate: zod.string().nullish(),
  taskCount: zod.number(),
  completedTaskCount: zod.number(),
  createdAt: zod.string(),
});

/**
 * @summary Update project
 */
export const UpdateProjectParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateProjectBody = zod.object({
  name: zod.string().nullish(),
  description: zod.string().nullish(),
  status: zod.string().nullish(),
  startDate: zod.string().nullish(),
  endDate: zod.string().nullish(),
});

export const UpdateProjectResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  description: zod.string().nullish(),
  departmentId: zod.number().nullish(),
  departmentName: zod.string().nullish(),
  status: zod.string(),
  createdBy: zod.number(),
  startDate: zod.string().nullish(),
  endDate: zod.string().nullish(),
  taskCount: zod.number(),
  completedTaskCount: zod.number(),
  createdAt: zod.string(),
});

/**
 * @summary Delete project
 */
export const DeleteProjectParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary List tasks
 */
export const ListTasksQueryParams = zod.object({
  projectId: zod.coerce.number().nullish(),
  assignedTo: zod.coerce.number().nullish(),
  status: zod.coerce.string().nullish(),
  priority: zod.coerce.string().nullish(),
});

export const ListTasksResponseItem = zod.object({
  id: zod.number(),
  projectId: zod.number().nullish(),
  projectName: zod.string().nullish(),
  title: zod.string(),
  description: zod.string().nullish(),
  assignedTo: zod.number().nullish(),
  assignedToName: zod.string().nullish(),
  createdBy: zod.number(),
  priority: zod.string(),
  status: zod.string(),
  dueDate: zod.string().nullish(),
  commentCount: zod.number(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});
export const ListTasksResponse = zod.array(ListTasksResponseItem);

/**
 * @summary Create a task
 */
export const CreateTaskBody = zod.object({
  projectId: zod.number().nullish(),
  title: zod.string(),
  description: zod.string().nullish(),
  assignedTo: zod.number().nullish(),
  priority: zod.string(),
  dueDate: zod.string().nullish(),
});

/**
 * @summary Get task by ID
 */
export const GetTaskParams = zod.object({
  id: zod.coerce.number(),
});

export const GetTaskResponse = zod.object({
  id: zod.number(),
  projectId: zod.number().nullish(),
  projectName: zod.string().nullish(),
  title: zod.string(),
  description: zod.string().nullish(),
  assignedTo: zod.number().nullish(),
  assignedToName: zod.string().nullish(),
  createdBy: zod.number(),
  priority: zod.string(),
  status: zod.string(),
  dueDate: zod.string().nullish(),
  commentCount: zod.number(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});

/**
 * @summary Update task
 */
export const UpdateTaskParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateTaskBody = zod.object({
  title: zod.string().nullish(),
  description: zod.string().nullish(),
  assignedTo: zod.number().nullish(),
  priority: zod.string().nullish(),
  status: zod.string().nullish(),
  dueDate: zod.string().nullish(),
});

export const UpdateTaskResponse = zod.object({
  id: zod.number(),
  projectId: zod.number().nullish(),
  projectName: zod.string().nullish(),
  title: zod.string(),
  description: zod.string().nullish(),
  assignedTo: zod.number().nullish(),
  assignedToName: zod.string().nullish(),
  createdBy: zod.number(),
  priority: zod.string(),
  status: zod.string(),
  dueDate: zod.string().nullish(),
  commentCount: zod.number(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});

/**
 * @summary Delete task
 */
export const DeleteTaskParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary List comments on a task
 */
export const ListTaskCommentsParams = zod.object({
  id: zod.coerce.number(),
});

export const ListTaskCommentsResponseItem = zod.object({
  id: zod.number(),
  taskId: zod.number(),
  userId: zod.number(),
  userFullName: zod.string(),
  avatarUrl: zod.string().nullish(),
  body: zod.string(),
  createdAt: zod.string(),
});
export const ListTaskCommentsResponse = zod.array(ListTaskCommentsResponseItem);

/**
 * @summary Add a comment to a task
 */
export const CreateTaskCommentParams = zod.object({
  id: zod.coerce.number(),
});

export const CreateTaskCommentBody = zod.object({
  body: zod.string(),
});

/**
 * @summary List notifications for current user
 */
export const ListNotificationsQueryParams = zod.object({
  isRead: zod.coerce.boolean().nullish(),
});

export const ListNotificationsResponseItem = zod.object({
  id: zod.number(),
  userId: zod.number(),
  type: zod.string(),
  title: zod.string(),
  body: zod.string(),
  entityType: zod.string().nullish(),
  entityId: zod.number().nullish(),
  isRead: zod.boolean(),
  createdAt: zod.string(),
});
export const ListNotificationsResponse = zod.array(
  ListNotificationsResponseItem,
);

/**
 * @summary Send notification (broadcast or targeted)
 */
export const CreateNotificationBody = zod.object({
  userId: zod.number().nullish(),
  departmentId: zod.number().nullish(),
  broadcast: zod.boolean(),
  type: zod.string(),
  title: zod.string(),
  body: zod.string(),
});

/**
 * @summary Mark notification as read
 */
export const MarkNotificationReadParams = zod.object({
  id: zod.coerce.number(),
});

export const MarkNotificationReadResponse = zod.object({
  id: zod.number(),
  userId: zod.number(),
  type: zod.string(),
  title: zod.string(),
  body: zod.string(),
  entityType: zod.string().nullish(),
  entityId: zod.number().nullish(),
  isRead: zod.boolean(),
  createdAt: zod.string(),
});

/**
 * @summary Mark all notifications as read
 */
export const MarkAllNotificationsReadResponse = zod.object({
  message: zod.string(),
});

/**
 * @summary Overall dashboard summary stats
 */
export const GetDashboardStatsResponse = zod.object({
  totalEmployees: zod.number(),
  presentToday: zod.number(),
  onLeaveToday: zod.number(),
  pendingLeaveRequests: zod.number(),
  pendingComplaints: zod.number(),
  pendingRequests: zod.number(),
  openTasks: zod.number(),
  payrollDue: zod.number(),
  recentActivity: zod.array(
    zod.object({
      id: zod.number(),
      type: zod.string(),
      description: zod.string(),
      actorName: zod.string(),
      createdAt: zod.string(),
    }),
  ),
});

/**
 * @summary Attendance report by department and date range
 */
export const GetAttendanceReportQueryParams = zod.object({
  startDate: zod.coerce.string(),
  endDate: zod.coerce.string(),
  departmentId: zod.coerce.number().nullish(),
});

export const GetAttendanceReportResponse = zod.object({
  totalPresent: zod.number(),
  totalAbsent: zod.number(),
  totalLate: zod.number(),
  byDepartment: zod.array(
    zod.object({
      departmentName: zod.string(),
      present: zod.number(),
      absent: zod.number(),
      late: zod.number(),
    }),
  ),
});

/**
 * @summary Leave utilization report
 */
export const GetLeaveReportQueryParams = zod.object({
  year: zod.coerce.number(),
  departmentId: zod.coerce.number().nullish(),
});

export const GetLeaveReportResponse = zod.object({
  totalApplications: zod.number(),
  approved: zod.number(),
  rejected: zod.number(),
  pending: zod.number(),
  byType: zod.array(
    zod.object({
      leaveType: zod.string(),
      count: zod.number(),
      totalDays: zod.number(),
    }),
  ),
});

/**
 * @summary Payroll report by period
 */
export const GetPayrollReportQueryParams = zod.object({
  month: zod.coerce.number(),
  year: zod.coerce.number(),
});

export const GetPayrollReportResponse = zod.object({
  totalNetSalary: zod.number(),
  totalBaseSalary: zod.number(),
  totalBonuses: zod.number(),
  totalDeductions: zod.number(),
  employeeCount: zod.number(),
  approvedCount: zod.number(),
});

/**
 * @summary Get company settings
 */
export const GetSettingsResponse = zod.object({
  id: zod.number(),
  companyName: zod.string(),
  logoUrl: zod.string().nullish(),
  timezone: zod.string(),
  workStartTime: zod.string(),
  workEndTime: zod.string(),
  payrollCycleDay: zod.number(),
  lateThresholdMinutes: zod.number(),
  updatedAt: zod.string(),
});

/**
 * @summary Update company settings
 */
export const UpdateSettingsBody = zod.object({
  companyName: zod.string().nullish(),
  logoUrl: zod.string().nullish(),
  timezone: zod.string().nullish(),
  workStartTime: zod.string().nullish(),
  workEndTime: zod.string().nullish(),
  payrollCycleDay: zod.number().nullish(),
  lateThresholdMinutes: zod.number().nullish(),
});

export const UpdateSettingsResponse = zod.object({
  id: zod.number(),
  companyName: zod.string(),
  logoUrl: zod.string().nullish(),
  timezone: zod.string(),
  workStartTime: zod.string(),
  workEndTime: zod.string(),
  payrollCycleDay: zod.number(),
  lateThresholdMinutes: zod.number(),
  updatedAt: zod.string(),
});

/**
 * @summary List audit logs (Super Admin only)
 */
export const ListAuditLogsQueryParams = zod.object({
  actorId: zod.coerce.number().nullish(),
  entityType: zod.coerce.string().nullish(),
  startDate: zod.coerce.string().nullish(),
  endDate: zod.coerce.string().nullish(),
});

export const ListAuditLogsResponseItem = zod.object({
  id: zod.number(),
  actorId: zod.number(),
  actorName: zod.string().nullish(),
  action: zod.string(),
  entityType: zod.string(),
  entityId: zod.number().nullish(),
  ipAddress: zod.string().nullish(),
  createdAt: zod.string(),
});
export const ListAuditLogsResponse = zod.array(ListAuditLogsResponseItem);
