/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ERP System API
 * OpenAPI spec version: 0.1.0
 */

export interface AttendanceSummary {
  userId: number;
  userFullName: string;
  departmentName: string;
  presentDays: number;
  absentDays: number;
  lateDays: number;
  workingDays: number;
}
