/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ERP System API
 * OpenAPI spec version: 0.1.0
 */

export interface AttendanceRecord {
  id: number;
  userId: number;
  /** @nullable */
  userFullName?: string | null;
  date: string;
  /** @nullable */
  clockInAt?: string | null;
  /** @nullable */
  clockOutAt?: string | null;
  isLate: boolean;
  /** @nullable */
  notes?: string | null;
  createdAt: string;
}
