/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ERP System API
 * OpenAPI spec version: 0.1.0
 */

export interface Complaint {
  id: number;
  userId: number;
  /** @nullable */
  userFullName?: string | null;
  departmentId: number;
  /** @nullable */
  departmentName?: string | null;
  category: string;
  title: string;
  description: string;
  isAnonymous: boolean;
  status: string;
  /** @nullable */
  assignedTo?: number | null;
  /** @nullable */
  assignedToName?: string | null;
  /** @nullable */
  response?: string | null;
  createdAt: string;
  updatedAt: string;
}
