/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ERP System API
 * OpenAPI spec version: 0.1.0
 */

export interface CreateUserBody {
  email: string;
  fullName: string;
  role: string;
  /** @nullable */
  departmentId?: number | null;
  /** @nullable */
  position?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  joinDate?: string | null;
  password: string;
}
