/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ERP System API
 * OpenAPI spec version: 0.1.0
 */

export interface Department {
  id: number;
  name: string;
  slug: string;
  /** @nullable */
  headUserId?: number | null;
  /** @nullable */
  headUserName?: string | null;
  employeeCount: number;
  createdAt: string;
}
