/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ERP System API
 * OpenAPI spec version: 0.1.0
 */
import type { LeaveTypeStat } from "./leaveTypeStat";

export interface LeaveReport {
  totalApplications: number;
  approved: number;
  rejected: number;
  pending: number;
  byType: LeaveTypeStat[];
}
