/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ERP System API
 * OpenAPI spec version: 0.1.0
 */

export type ListAuditLogsParams = {
  /**
   * @nullable
   */
  actorId?: number | null;
  /**
   * @nullable
   */
  entityType?: string | null;
  /**
   * @nullable
   */
  startDate?: string | null;
  /**
   * @nullable
   */
  endDate?: string | null;
};
