/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ERP System API
 * OpenAPI spec version: 0.1.0
 */

export interface Notification {
  id: number;
  userId: number;
  type: string;
  title: string;
  body: string;
  /** @nullable */
  entityType?: string | null;
  /** @nullable */
  entityId?: number | null;
  isRead: boolean;
  createdAt: string;
}
