/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ERP System API
 * OpenAPI spec version: 0.1.0
 */

export interface PayrollReport {
  totalNetSalary: number;
  totalBaseSalary: number;
  totalBonuses: number;
  totalDeductions: number;
  employeeCount: number;
  approvedCount: number;
}
