/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ERP System API
 * OpenAPI spec version: 0.1.0
 */

export interface PayrollRecord {
  id: number;
  userId: number;
  /** @nullable */
  userFullName?: string | null;
  /** @nullable */
  departmentName?: string | null;
  month: number;
  year: number;
  baseSalary: number;
  allowances: number;
  bonuses: number;
  deductions: number;
  netSalary: number;
  status: string;
  /** @nullable */
  approvedBy?: number | null;
  /** @nullable */
  approvedByName?: string | null;
  createdAt: string;
  updatedAt: string;
}
