/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ERP System API
 * OpenAPI spec version: 0.1.0
 */

export interface Task {
  id: number;
  /** @nullable */
  projectId?: number | null;
  /** @nullable */
  projectName?: string | null;
  title: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  assignedTo?: number | null;
  /** @nullable */
  assignedToName?: string | null;
  createdBy: number;
  priority: string;
  status: string;
  /** @nullable */
  dueDate?: string | null;
  commentCount: number;
  createdAt: string;
  updatedAt: string;
}
