/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ERP System API
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateComplaintBody {
  /** @nullable */
  status?: string | null;
  /** @nullable */
  response?: string | null;
  /** @nullable */
  assignedTo?: number | null;
}
