/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ERP System API
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateSettingsBody {
  /** @nullable */
  companyName?: string | null;
  /** @nullable */
  logoUrl?: string | null;
  /** @nullable */
  timezone?: string | null;
  /** @nullable */
  workStartTime?: string | null;
  /** @nullable */
  workEndTime?: string | null;
  /** @nullable */
  payrollCycleDay?: number | null;
  /** @nullable */
  lateThresholdMinutes?: number | null;
}
